#!/usr/bin/env bash

notmuch tag +muni -- tag:new and from:muni.cz
notmuch tag +twitter -- tag:new and from:twitter.com

notmuch tag +logio -- tag:new and to:logio.cz
notmuch tag +logio -- tag:new and from:logio.cz

notmuch tag +saleschamp -- tag:new and to:saleschamp.nl
notmuch tag +saleschamp -- tag:new and from:saleschamp.nl

# newsletters
notmuch tag +newsletter -- tag:new and from:jakub@programmingdigest.net
notmuch tag +newsletter -- tag:new and from:newsletter@brainpickings.org
notmuch tag -inbox -- tag:newsletter

# finally, retag all "new" messages "inbox" and "unread"
notmuch tag +inbox -new -- tag:new
