#!/usr/bin/env bash

notmuch tag +muni -- tag:new and from:muni.cz
notmuch tag +twitter -- tag:new and from:twitter.com

notmuch tag +logio -- tag:new and to:logio.cz
notmuch tag +logio -- tag:new and from:logio.cz

notmuch tag +saleschamp -- tag:new and to:saleschamp
notmuch tag +saleschamp -- tag:new and from:saleschamp

# newsletters
notmuch tag +newsletter -- tag:new and from:jakub@programmingdigest.net

notmuch tag -unread -- tag:new and tag:newsletter

# Saleschamp related spam
notmuch tag -unread +deleted -- tag:new and from:jira@saleschamp.atlassian.net
notmuch tag -unread +deleted -- tag:new and from:noreply@md.getsentry.com and not weekly

# Github
notmuch tag +github -- tag:new and notifications@github.com
notmuch tag -unread -- tag:new and tag:github

# Decide what we want to keep in inbox
notmuch tag +inbox -- tag:new
notmuch tag -inbox -- tag:newsletter or tag:archived

# Make sure deleted and uninteresting things are removed from unread queue
notmuch tag -unread -- tag:new and tag:deleted
notmuch tag -new -- tag:new
