#!/usr/bin/env bash

notmuch tag +muni -- tag:new and from:muni.cz
notmuch tag +logio -- tag:new and to:logio.cz
notmuch tag +logio -- tag:new and from:logio.cz
notmuch tag +twitter -- tag:new and from:twitter.com

# finally, retag all "new" messages "inbox" and "unread"
notmuch tag +inbox -new -- tag:new
